### PR TITLE
ci: travis

### PR DESCRIPTION
**Pull request by jcvenegas**
Use TRAVIS branch to checkout test repository

Fixes: #79

### CODE REVIEW

**Comment by ganeshmaharaj** [comment]
Need to rebase the branch to latest master to pick up all the linter related changes.

**Comment by egernst** [comment]
GitHb should handle that, no?

**Comment by ganeshmaharaj** [comment]
Not sure how we tell travis to rebase the branch to the latest tree prior to running the tests.

**Comment by jcvenegas** [comment]
rebased

**Comment by jcvenegas** [comment]
```
evel=info msg="[test] stderr: "
--- FAIL: TestNotExistingDirRun (0.58s)
    testshared.go:67: 
        	Error Trace:	testshared.go:67
        	            				run_test.go:35
        	Error:      	"level=warning msg="[runner/megacheck] Can't run megacheck because of compilation errors in packages [_/home/travis/gopath/src/github.com/golangci/golangci-lint/test/testdata/no_such_dir]: -: cannot find package \".\" in:\n\t/home/travis/gopath/src/github.com/golangci/golangci-lint/test/testdata/no_such_dir"
        	            	level=error msg="[runner/typecheck] typechecking error: cannot find package \".\" in:\n\t/home/travis/gopath/src/github.com/golangci/golangci-lint/test/testdata/no_such_dir"
        	            	" does not contain "cannot find package \"./testdata/no_such_dir\""
        	Test:       	TestNotExistingDirRun
        	Messages:   	exit code is 2
```
Linter build failing in go tip ... not related with this commit, safe to merge

**Pull request merged**
