### PR TITLE
build: Fix systemd unit file build error

### LINKED ISSUE #47: Fix build systemd unit file build error
#38 renamed the target for building the throttler unit file but did not include the file rename.

### PR DESCRIPTION
**Pull request by jodh-intel**
PR #38 renamed the target for building the throttler unit file but did
not include the file rename which caused the build to fail with:

```
make: *** No rule to make target 'kata-ksm-throttler.service.in', needed by 'kata-ksm-throttler.service'.  Stop.
```

Fixes #47.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Ping @chavafg.

**Comment by chavafg** [comment]
lgtm

**Comment by jodh-intel** [comment]
Um, not sure why @jcvenegas's ack isn't working for pullapprove seeing as he wrote osbuilder! :)

Merging...

**Comment by jodh-intel** [comment]
Umm, wrong repo ;) Holding fire to give @grahamwhaley a chance to review...

**Pull request merged**
