### PR TITLE
# Kata Containers 1.5.4

### PR DESCRIPTION
**Pull request by katacontainersbot**
- # Kata Containers 1.5.3
- ci: travis
- # Kata Containers 1.5.2
- # Kata Containers 1.5.1
- Stable 1.5.1 rc backports

c0039de ci: travis
6eabb81 release: Kata Containers 1.5.3
4ce8611 release: Kata Containers 1.5.2
a9c4d08 release: Kata Containers 1.5.1
2a16e09 pullapprove: remove it
150a590 make: do not rebuild build artifacts on install

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Hi @jcvenegas - I'm going to presume the occurence of 1.5.[1234] in this is an artifact of the release bot/scripts that we are probably ironing out?

**Comment by jodh-intel** [comment]
@jcvenegas, @egernst - looks like you'll have to add a commit for the Travis config file to this PR :)...

```
INFO: Checking for SPDX license headers
ERROR: Required license identifier ('SPDX-License-Identifier: Apache-2.0') missing from following files:

.travis.yml
```

**Comment by jcvenegas** [comment]
@grahamwhaley yep, it is the script, let me see what is the bug

**Comment by jcvenegas** [comment]
Closing this PR we are tagging the this repo based on master. I'll fix the script to not bump ksm and osbuilder on stable branches.

**Pull request closed without merging**
