### PR TITLE
Require 2 pullapprove acks

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Comment by WeiZhang555** [comment]
LGTM

**Comment by bergwolf** [comment]
LGTM

**Comment by bergwolf** [comment]
` .pullapprove.yml proposed by this PR is invalid`

**Comment by jodh-intel** [comment]
Hi @bergwolf - Where were you seeing the "invalid" message mentioned in https://github.com/kata-containers/ksm-throttler/pull/7#issuecomment-352679383 ?

**Comment by bergwolf** [comment]
@jodh-intel It was reported by pullapprove.com in this PR. I'm not sure if it was just intermediate.

**Pull request merged**
