### PR TITLE
doc: add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by caoruidong**
add a minimal CONTRIBUTING.md for this repo

Fixes: #17

Signed-off-by: Ruidong Cao <caoruidong@huawei.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by sameo** [comment]
LGTM

**Comment by sameo** [comment]
@caoruidong Could you please rebase?

**Comment by caoruidong** [comment]
@sameo Done

**Pull request merged**
