### PR TITLE
# Kata Containers 1.4.2

### PR DESCRIPTION
**Pull request by bergwolf**
bump version no change.

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by grahamwhaley** [comment]
Having that '1.4.1' in the PR body (in a large font bullet point) is confusing! I *think* it is because the only commit, or the top commit, in the changeset is the 1.4.1 tag - and the automation scripts have picked that up and used it as the title. Is this bothering anybody else? :-)

**Comment by bergwolf** [comment]
@egernst @grahamwhaley commit message updated. PTAL

**Comment by liwei** [comment]
lgtm

**Pull request merged**
