### PR TITLE
ci: lib: allow override of tests_repo

### PR DESCRIPTION
**Pull request by grahamwhaley**
Only set the default tests_repo url if one is not already set.

Fixes: #30

Signed-off-by: Graham whaley <graham.whaley@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
phew, I think that's the last one...

**Comment by jodh-intel** [comment]
lgtm

**Comment by grahamwhaley** [comment]
rebased - let's see if the CI is happier now...

**Comment by grahamwhaley** [comment]
tada - now just missing one more ack from @kata-containers/throttler group...

**Comment by grahamwhaley** [comment]
@jodh-intel - we have a couple of acks, and the CI is good, and this is trivial, and nobody is responding - so, if you fancy, I'd be happy (and biased of course) if you wanted to just push this through ;-)

**Comment by caoruidong** [comment]
Looks like chavafg not in throttler team. So his "lgtm" doesn't count.
Why it says "This branch is out-of-date with the base branch" ? Can we merge this?

**Comment by grahamwhaley** [comment]
Branch is out of date because we landed #40 yesterday I think - but, that should not affect this. I rebased this just before #40 iirc. That github message is just a warning - I think if it is not mergeable then you get a 'stronger' warning saying 'cannot be merged'.

**Comment by caoruidong** [comment]
@grahamwhaley Whoops，I did something wrong. Merge this to see if it's all right.

**Pull request merged**
