### PR TITLE
trigger: Fix virtcontainers paths

### LINKED ISSUE #37: Update virtcontainers trigger for new virtcontainers path
The throttler's vc trigger is still looking at `/run/virtcontainers/pods/`, which is no longer valid.

### PR DESCRIPTION
**Pull request by jodh-intel**
Update for the new Virtcontainers root directory.

See:

- https://github.com/kata-containers/runtime/pull/200
- https://github.com/kata-containers/runtime/pull/294

Also, a number of tidy-up commits including changes to ensure files and paths are Kata specific.

Fixes #37.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Ping @kata-containers/throttler - it would be great to get this landed as it unbreaks the throttler... ;)

**Comment by jodh-intel** [comment]
Hi @klynnrif - ptal at the tiny doc change.

**Comment by sboeuf** [comment]
@jodh-intel any update on this one ?

**Comment by jodh-intel** [comment]
Umm. Manana I think ;)

**Comment by devimc** [comment]
Note to self: buy cookies and milk  :smile:

**Comment by jodh-intel** [comment]
Hi @caoruidong - it's updated! :)

**Comment by jodh-intel** [comment]
Ping @kata-containers/throttler.

**Comment by sameo** [comment]
LGTM

**Pull request merged**
