### PR TITLE
github: Add issue template

### LINKED ISSUE #28: Add github issue template
Copy https://github.com/kata-containers/runtime/blob/master/.github/ISSUE_TEMPLATE.md into this repo.

### PR DESCRIPTION
**Pull request by jodh-intel**
Add a template to guide the user on raising github issues.

Fixes #28.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
The collect script doesn't actually collect data on the throttler yet, but [it will soon](https://github.com/kata-containers/runtime/issues/103) so let's add the template now anyway.

**Comment by jodh-intel** [comment]
Hi @klynnrif - ptal. This is the last of the identical issue template PRs I think.

**Comment by WeiZhang555** [comment]
LGTM :+1:

**Comment by grahamwhaley** [comment]
Blocked on #25 right now (for CI/linters)

**Pull request merged**
